const STUDENT_DATABASE = {
    "690736": { title: "นาย", fname: "กฤติน", lname: "ทองทา", room: "7", no: "1", role: "head" },
    "690737": { title: "นางสาว", fname: "กวินธิดา", lname: "นักค้า", room: "7", no: "2", role: "student" },
    "690738": { title: "นาย", fname: "กันต์ธัช", "lname": "สุขะ", room: "7", no: "3", role: "student" },
    "690742": { title: "นาย", fname: "ซอดิ๊ค", lname: "ตติยะภูรี", room: "7", no: "4", role: "student" },
    "690743": { title: "นางสาว", fname: "ญาณิพัชญ์", lname: "หัสดี", room: "7", no: "5", role: "student" },
    "690744": { title: "นาย", fname: "ณฐกฤช", lname: "ผดุงนึก", room: "7", no: "6", role: "student" },
    "690745": { title: "นาย", fname: "ณัชฐปกรณ์", lname: "รินชุมภู", room: "7", no: "7", role: "student" },
    "690747": { title: "นางสาว", fname: "ดนยา", lname: "กนกศีชริน", room: "7", no: "8", role: "student" },
    "690750": { title: "นาย", fname: "ธนโชติ", lname: "นาคน้ำ", room: "7", no: "9", role: "student" },
    "690754": { title: "นาย", fname: "ธีธัช", lname: "ศรีรุวัฒน์", room: "7", no: "10", role: "student" },
    "690759": { title: "นาย", fname: "ปภินวิช", lname: "ศิรินาม", room: "7", no: "11", role: "student" },
    "690762": { title: "นาย", fname: "ปรัตถกร", lname: "เซโตะ", room: "7", no: "12", role: "student" },
    "690764": { title: "นางสาว", fname: "ปวันรัตน์", lname: "อุรุทิศ", room: "7", no: "13", role: "student" },
    "690771": { title: "นาย", fname: "ภัทรพล", lname: "สุรินทร์", room: "7", no: "14", role: "student" },
    "690773": { title: "นาย", fname: "ภิชญะ", lname: "ตั้งใจรักษา", room: "7", no: "15", role: "student" },
    "690774": { title: "นาย", fname: "ภูดิศ", lname: "ประชาสิทธิศักดิ์", room: "7", no: "16", role: "student" },
    "690775": { title: "นาย", fname: "เมธาสิทธิ์", lname: "ปินทะนา", room: "7", no: "17", role: "student" },
    "690776": { title: "นาย", fname: "โรเบิร์ต กาย", lname: "ทอมเบอลิน", room: "7", no: "18", role: "student" },
    "690777": { title: "นาย", fname: "วงศ์ศพัทธ์", lname: "อินอ่อน", room: "7", no: "19", role: "student" },
    "690778": { title: "นาย", fname: "วรพงศ์", lname: "ลิ้มจำรูญรัตน์", room: "7", no: "20", role: "admin" }, // คุณ (แอดมิน)
    "690779": { title: "นางสาว", fname: "วริศรา", lname: "เจริญผล", room: "7", no: "21", role: "student" },
    "690783": { title: "นาย", fname: "เศรษฐ์ภวิศ", lname: "กุลสิทธิ์", room: "7", no: "22", role: "student" },
    "690784": { title: "นาย", fname: "สถิตเทพ", lname: "มุ้งทอง", room: "7", no: "23", role: "student" },
    "690786": { title: "นาย", fname: "สรรภพ", lname: "คำพิงชัย", room: "7", no: "24", role: "student" },
    "690787": { title: "นาย", fname: "สิรภพ", lname: "กันธิยะ", room: "7", no: "25", role: "student" },
    "690789": { title: "นางสาว", fname: "สุธนี", "lname": "ใจมา", room: "7", no: "26", role: "student" },
    "690790": { title: "นางสาว", fname: "สุประวีญาภรณ์", lname: "ศักดิ์ศรี", room: "7", no: "27", role: "student" },
    "690792": { title: "นางสาว", fname: "อรกัญญา", lname: "อุดมความสุข", room: "7", no: "28", role: "student" },
    "690793": { title: "นาย", fname: "อัครวิช", lname: "คำวัง", room: "7", no: "29", role: "student" },
    "690794": { title: "นางสาว", fname: "อาพิรัตยา", lname: "ปีบ้านใหม่", room: "7", no: "30", role: "head" }
};